set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	
set_property PACKAGE_PIN V17 [get_ports {reset}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
set_property PACKAGE_PIN V16 [get_ports {en}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {en}]	

set_property PACKAGE_PIN U2 [get_ports anode_active[0]] 
set_property IOSTANDARD LVCMOS33 [get_ports anode_active[0]]
set_property PACKAGE_PIN U4 [get_ports anode_active[1]] 
set_property IOSTANDARD LVCMOS33 [get_ports anode_active[1]] 
set_property PACKAGE_PIN V4 [get_ports anode_active[2]] 
set_property IOSTANDARD LVCMOS33 [get_ports anode_active[2]] 
set_property PACKAGE_PIN W4 [get_ports anode_active[3]] 
set_property IOSTANDARD LVCMOS33 [get_ports anode_active[3]] 

set_property PACKAGE_PIN W7 [get_ports segments[6]] 
set_property IOSTANDARD LVCMOS33 [get_ports segments[6]] 
set_property PACKAGE_PIN W6 [get_ports segments[5]] 
set_property IOSTANDARD LVCMOS33 [get_ports segments[5]] 
set_property PACKAGE_PIN U8 [get_ports segments[4]] 
set_property IOSTANDARD LVCMOS33 [get_ports segments[4]] 
set_property PACKAGE_PIN V8 [get_ports segments[3]] 
set_property IOSTANDARD LVCMOS33 [get_ports segments[3]] 
set_property PACKAGE_PIN U5 [get_ports segments[2]] 
set_property IOSTANDARD LVCMOS33 [get_ports segments[2]] 
set_property PACKAGE_PIN V5 [get_ports segments[1]] 
set_property IOSTANDARD LVCMOS33 [get_ports segments[1]] 
set_property PACKAGE_PIN U7 [get_ports segments[0]] 
set_property IOSTANDARD LVCMOS33 [get_ports segments[0]]
