
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	
set_property PACKAGE_PIN V17 [get_ports {reset}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
set_property PACKAGE_PIN V16 [get_ports {en}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {en}]
	
set_property PACKAGE_PIN U16 [get_ports {digitSeconds[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digitSeconds[0]}]
set_property PACKAGE_PIN E19 [get_ports {digitSeconds[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digitSeconds[1]}]
set_property PACKAGE_PIN U19 [get_ports {digitSeconds[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digitSeconds[2]}]
set_property PACKAGE_PIN V19 [get_ports {digitSeconds[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digitSeconds[3]}]
set_property PACKAGE_PIN W18 [get_ports {tensSeconds[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {tensSeconds[0]}]
set_property PACKAGE_PIN U15 [get_ports {tensSeconds[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {tensSeconds[1]}]
set_property PACKAGE_PIN U14 [get_ports {tensSeconds[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {tensSeconds[2]}]
set_property PACKAGE_PIN V14 [get_ports {digitMinutes[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digitMinutes[0]}]
set_property PACKAGE_PIN V13 [get_ports {digitMinutes[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digitMinutes[1]}]
set_property PACKAGE_PIN V3 [get_ports {digitMinutes[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digitMinutes[2]}]
set_property PACKAGE_PIN W3 [get_ports {digitMinutes[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digitMinutes[3]}]
set_property PACKAGE_PIN U3 [get_ports {tensMinutes[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {tensMinutes[0]}]
set_property PACKAGE_PIN P3 [get_ports {tensMinutes[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {tensMinutes[1]}]
set_property PACKAGE_PIN N3 [get_ports {tensMinutes[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {tensMinutes[2]}]

